"""empty message

Revision ID: 023f803b6402
Revises: None
Create Date: 2016-12-22 10:30:44.741000

"""

# revision identifiers, used by Alembic.
revision = '023f803b6402'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freights', sa.Column('is_courier_chosen', sa.BOOLEAN(), nullable=True))
    op.add_column('freights', sa.Column('is_delivered', sa.BOOLEAN(), nullable=True))
    op.add_column('tender', sa.Column('approved', sa.BOOLEAN(), nullable=True))
    op.add_column('tender', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('tender', sa.Column('suggested_price', sa.REAL(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender', 'suggested_price')
    op.drop_column('tender', 'description')
    op.drop_column('tender', 'approved')
    op.drop_column('freights', 'is_delivered')
    op.drop_column('freights', 'is_courier_chosen')
    ### end Alembic commands ###
