"""empty message

Revision ID: ca065431ae43
Revises: None
Create Date: 2016-09-16 03:24:21.331000

"""

# revision identifiers, used by Alembic.
revision = 'ca065431ae43'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freight_pictures', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('freights', sa.Column('creation_data', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freights', 'creation_data')
    op.drop_column('freight_pictures', 'created')
    ### end Alembic commands ###
